### ISSUE TITLE
Add an icon and a desktop file for the jack application

### ISSUE THREAD

**Issue by ycollet** [jpcima/spectacle#18]
Add an icon and a desktop file for spectacle-analyzer.
I added this one in the Fedora package:
```
[Desktop Entry]
Version=1.0
Name=Spectacle Analyzer
Comment=Realtime graphical spectrum analyzer
Exec=spectacle-analyzer
Icon=spectacle
Terminal=false
Type=Application
Categories=Audio;AudioVideo;
```

**Comment by jpcima** [comment]
> I added this one in the Fedora package:

What do you use for the icon? I have yet to make one.

**Comment by trebmuh** [comment]
Il faudrait ajouter également :
>Comment[fr}=Analyseur graphique de spectre en temps réel

en dessous de la ligne "Comment=..."

**Comment by jpcima** [comment]
Also `Icon=spectacle` must change, because of the software name conflict

**Comment by trebmuh** [comment]
@ycollet : je te laisse faire un PR ?

**Comment by ycollet** [comment]
OK, I will do this.
@jpcima , can you commit and icon ?

**Comment by jpcima** [comment]
> can you commit and icon ?

Ok, desktop file is in 789653e.
There isn't an icon.

**Comment by jpcima** [comment]
The icon is made thanks to @trebmuh, and is added to the `make install` rule.
