### ISSUE TITLE
Use a standard license which GitHub can read

### ISSUE THREAD

**Issue by kmturley** [jpcima/spectacle#23]
Hi there!
Thank-you for the amazing plugin!

You already have a LICENSE file here:
https://github.com/jpcima/spectacle/blob/master/LICENSE

However because it is not a standard template, GitHub cannot display the license. It also requires all users to read the LICENSE end-to-end to understand what type of license it is.

Would you be able to use a standard template to make it easier to understand and search for?
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Thanks!

**Comment by jpcima** [comment]
Hello, the file changed according to template, does it look correct now?

**Comment by kmturley** [comment]
Yes it works! Now when you view the file GitHub shows enriched information:
https://github.com/jpcima/spectacle/blob/master/LICENSE

This also means the license is available via Search and API:
https://api.github.com/repos/jpcima/spectacle

Thank-you for the quick turnaround!
