### ISSUE TITLE
Different Color schemes?

### ISSUE THREAD

**Issue by unfa** [jpcima/spectacle#3]
I'd love to be able to change the colors.

**Comment by unfa** [comment]
I see there's been some work done to enable color schemes, but it's unfinished - right?

**Comment by jpcima** [comment]
It works and can be used, this is for a quick summary of how it goes
- on launch you will get a folder `~/.config/Spectacle/themes`
- user is supposed to duplicate `default.ini` with another name, `mytheme.ini`
- select `mytheme` in the "Color" popup
- enable Edit mode. plugin will detect edits and they take immediate effect

**Comment by jpcima** [comment]
@unfa current problems should be resolved
- color scheme
- resizing in carla

also
- new multirate algorithms as default, to increase resolution in LF range
- minor grid lines

still to-do
- not RT-safe to change STFT settings / algorithm
