### ISSUE TITLE
Framerate drops when using highest resolution and maximiznig the window to 1080p

### ISSUE THREAD

**Issue by unfa** [jpcima/spectacle#5]
To reproduce:

1. Set the FFT resolution to maximum
2. Maximize the window on a 1920x1080 screen.

Notice the animation is less smooth now. When dropping one notch down from the highest FFT resolution, it's fine again, but it's also perfectly smoothly animated when I decrease the window size.

This seems like some drawing issue, not DSP bottleneck to me.

My system specs:

```
Ryzen 7 1700
Radeon RX580
Manjaro 18 KDE
Ardour 5.12
```

**Comment by jpcima** [comment]
The current program is not GPU-rendered, all graphics computation are made in software.
It's the reason why it's slow, and I hope to change this in future versions.

Initially, I've wanted to make it GPU but met some obstacles, and decided that software was a faster path to results for time being.

The plan is to ship the first version without GPU in short schedule, and this will be one of the priority tasks.

**Comment by unfa** [comment]
I see, thank you for the explanation! I assumed it was drawn with OpenGL :)

**Comment by jpcima** [comment]
I've merged the openGL conversion into the master branch, this should be good.
I don't recall if there remained outstanding issues because I changed computer meanwhile and the former was on Intel graphics.
All seems ok apart from some drawing artifacts while resizing.

This adds custom edits of DPF, so don't forget to refresh the submodule if building from source.

**Comment by unfa** [comment]
Nice! I hope if we can get resizing working I could start using Spectacle for my videos and livestreams! The option to hide UI is excellent for that!

**Comment by jpcima** [comment]
> Nice! I hope if we can get resizing working I could start using Spectacle for my videos and livestreams! The option to hide UI is excellent for that!

Great, I know that it's been a year and this program has been stagnant, but I really wish to resume the work and bring it to completion, with sfizz now somewhat stabilized.

Given the state of the DPF framework, I'll take the wolf-spectrum approach to resizing.
Beside I have asked @alcomposer for suggestions on improving the display, and I'd take your suggestions also.

currently on my list
- neutral tone color for background to distinguish the 2 signals better (black/gray)
- imitate the spectrafoo displays. use green/pink for channels colors
- change fontawesome button icons to something less bold
